// Copyright (C) Microsoft Corporation. All rights reserved.

//
// NOTE: This header is generated by stubwork.  Please make any 
//       modifications to the corresponding template files 
//       (.x or .y) and use stubwork to regenerate the header
//

#ifndef _NETADAPTERCXPREVIEW_2_3_H_
#define _NETADAPTERCXPREVIEW_2_3_H_

#ifndef WDF_EXTERN_C
  #ifdef __cplusplus
    #define WDF_EXTERN_C       extern "C"
    #define WDF_EXTERN_C_START extern "C" {
    #define WDF_EXTERN_C_END   }
  #else
    #define WDF_EXTERN_C
    #define WDF_EXTERN_C_START
    #define WDF_EXTERN_C_END
  #endif
#endif

WDF_EXTERN_C_START




#ifdef NETCX_ADAPTER_PREVIEW
#error NETCX_ADAPTER_PREVIEW previously defined. NETCX_ macro prefix is reserved
#endif

#define NETCX_ADAPTER_PREVIEW
#include <netadaptercxtypes.h>
#include <preview/netfuncenum.h>
#include <netadaptercx.h>
#undef NETCX_ADAPTER_PREVIEW




WDF_EXTERN_C_END

#endif // _NETADAPTERCXPREVIEW_2_3_H_

