/*++

Copyright (c) Microsoft Corporation.  All rights reserved.

_WdfVersionBuild_

Module Name: NetTraceEnums.h

Abstract:
    Generated trace enums

Environment:
    kernel mode only

--*/

#ifndef _NETTRACEENUMS_H_
#define _NETTRACEENUMS_H_

#ifndef WDF_EXTERN_C
  #ifdef __cplusplus
    #define WDF_EXTERN_C       extern "C"
    #define WDF_EXTERN_C_START extern "C" {
    #define WDF_EXTERN_C_END   }
  #else
    #define WDF_EXTERN_C
    #define WDF_EXTERN_C_START
    #define WDF_EXTERN_C_END
  #endif
#endif

WDF_EXTERN_C_START

// begin_wpp config
// CUSTOM_TYPE(NET_ADAPTER_PAUSE_FUNCTION_TYPE, ItemEnum(_NET_ADAPTER_PAUSE_FUNCTION_TYPE));
// CUSTOM_TYPE(NET_ADAPTER_AUTO_NEGOTIATION_FLAGS, ItemEnum(_NET_ADAPTER_AUTO_NEGOTIATION_FLAGS));
// CUSTOM_TYPE(NET_MEMORY_MAPPING_REQUIREMENT, ItemEnum(_NET_MEMORY_MAPPING_REQUIREMENT));
// CUSTOM_TYPE(NET_ADAPTER_WAKE_PATTERN_ID, ItemEnum(_NET_ADAPTER_WAKE_PATTERN_ID));
// CUSTOM_TYPE(NET_PACKET_FILTER_FLAGS, ItemEnum(_NET_PACKET_FILTER_FLAGS));
// CUSTOM_TYPE(NET_ADAPTER_TX_DEMUX_TYPE, ItemEnum(_NET_ADAPTER_TX_DEMUX_TYPE));
// CUSTOM_TYPE(NET_CONFIGURATION_QUERY_ULONG_FLAGS, ItemEnum(_NET_CONFIGURATION_QUERY_ULONG_FLAGS));
// CUSTOM_TYPE(NET_POWER_OFFLOAD_TYPE, ItemEnum(_NET_POWER_OFFLOAD_TYPE));
// CUSTOM_TYPE(NET_ADAPTER_RECEIVE_SCALING_UNHASHED_TARGET_TYPE, ItemEnum(_NET_ADAPTER_RECEIVE_SCALING_UNHASHED_TARGET_TYPE));
// CUSTOM_TYPE(NET_ADAPTER_RECEIVE_SCALING_HASH_TYPE, ItemEnum(_NET_ADAPTER_RECEIVE_SCALING_HASH_TYPE));
// CUSTOM_TYPE(NET_ADAPTER_RECEIVE_SCALING_PROTOCOL_TYPE, ItemEnum(_NET_ADAPTER_RECEIVE_SCALING_PROTOCOL_TYPE));
// CUSTOM_TYPE(NET_ADAPTER_RECEIVE_SCALING_ENCAPSULATION_TYPE, ItemEnum(_NET_ADAPTER_RECEIVE_SCALING_ENCAPSULATION_TYPE));
// CUSTOM_TYPE(NET_WAKE_SOURCE_TYPE, ItemEnum(_NET_WAKE_SOURCE_TYPE));
// end_wpp

WDF_EXTERN_C_END

#endif // _NETTRACEENUMS_H_

