//
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//

#pragma once

EXTERN_C_START

//
// Kernel Mode Driver Interface
//

#define FUNCTIONAL_TEST_DRIVER_NAME "xdpfunctionaltestdrv"

#define IoGetFunctionCodeFromCtlCode( ControlCode ) (\
    ( ControlCode >> 2) & 0x00000FFF )

//
// IOCTL Interface
//

#define IOCTL_LOAD_API \
    CTL_CODE(FILE_DEVICE_NETWORK, 1, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_GENERIC_BINDING \
    CTL_CODE(FILE_DEVICE_NETWORK, 2, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_GENERIC_BINDING_RESET_ADAPTER \
    CTL_CODE(FILE_DEVICE_NETWORK, 3, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_GENERIC_RX_SINGLE_FRAME \
    CTL_CODE(FILE_DEVICE_NETWORK, 4, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_GENERIC_RX_NO_POKE \
    CTL_CODE(FILE_DEVICE_NETWORK, 5, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_GENERIC_RX_BACKFILL_AND_TRAILER \
    CTL_CODE(FILE_DEVICE_NETWORK, 6, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_GENERIC_RX_LOW_RESOURCES \
    CTL_CODE(FILE_DEVICE_NETWORK, 7, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_GENERIC_RX_MULTI_SOCKET \
    CTL_CODE(FILE_DEVICE_NETWORK, 8, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_GENERIC_RX_MULTI_PROGRAM \
    CTL_CODE(FILE_DEVICE_NETWORK, 9, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_GENERIC_TX_TO_RX_INJECT \
    CTL_CODE(FILE_DEVICE_NETWORK, 10, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_GENERIC_TX_SINGLE_FRAME \
    CTL_CODE(FILE_DEVICE_NETWORK, 11, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_GENERIC_TX_OUT_OF_ORDER \
    CTL_CODE(FILE_DEVICE_NETWORK, 12, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_GENERIC_TX_SHARING \
    CTL_CODE(FILE_DEVICE_NETWORK, 13, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_GENERIC_TX_POKE \
    CTL_CODE(FILE_DEVICE_NETWORK, 14, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_GENERIC_TX_MTU \
    CTL_CODE(FILE_DEVICE_NETWORK, 15, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_GENERIC_RX_TCP_CONTROL_V4 \
    CTL_CODE(FILE_DEVICE_NETWORK, 16, METHOD_BUFFERED, FILE_WRITE_DATA)
    // ADDRESS_FAMILY

#define IOCTL_GENERIC_RX_TCP_CONTROL_V6 \
    CTL_CODE(FILE_DEVICE_NETWORK, 17, METHOD_BUFFERED, FILE_WRITE_DATA)
    // ADDRESS_FAMILY

#define IOCTL_GENERIC_RX_ALL_QUEUE_REDIRECT_V4 \
    CTL_CODE(FILE_DEVICE_NETWORK, 18, METHOD_BUFFERED, FILE_WRITE_DATA)
    // ADDRESS_FAMILY

#define IOCTL_GENERIC_RX_ALL_QUEUE_REDIRECT_V6 \
    CTL_CODE(FILE_DEVICE_NETWORK, 19, METHOD_BUFFERED, FILE_WRITE_DATA)
    // ADDRESS_FAMILY

typedef struct {
    ADDRESS_FAMILY Af;
    XDP_MATCH_TYPE MatchType;
    BOOLEAN IsUdp;
} GENERIC_RX_MATCH_PARAMS;

#define IOCTL_GENERIC_RX_MATCH_UDP_V4 \
    CTL_CODE(FILE_DEVICE_NETWORK, 20, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_RX_MATCH_PARAMS

#define IOCTL_GENERIC_RX_MATCH_UDP_V6 \
    CTL_CODE(FILE_DEVICE_NETWORK, 21, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_RX_MATCH_PARAMS

#define IOCTL_GENERIC_RX_MATCH_UDP_PORT_V4 \
    CTL_CODE(FILE_DEVICE_NETWORK, 22, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_RX_MATCH_PARAMS

#define IOCTL_GENERIC_RX_MATCH_UDP_PORT_V6 \
    CTL_CODE(FILE_DEVICE_NETWORK, 23, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_RX_MATCH_PARAMS

#define IOCTL_GENERIC_RX_MATCH_UDP_TUPLE_V4 \
    CTL_CODE(FILE_DEVICE_NETWORK, 24, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_RX_MATCH_PARAMS

#define IOCTL_GENERIC_RX_MATCH_UDP_TUPLE_V6 \
    CTL_CODE(FILE_DEVICE_NETWORK, 25, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_RX_MATCH_PARAMS

#define IOCTL_GENERIC_RX_MATCH_UDP_QUIC_SRC_V4 \
    CTL_CODE(FILE_DEVICE_NETWORK, 26, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_RX_MATCH_PARAMS

#define IOCTL_GENERIC_RX_MATCH_UDP_QUIC_SRC_V6 \
    CTL_CODE(FILE_DEVICE_NETWORK, 27, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_RX_MATCH_PARAMS

#define IOCTL_GENERIC_RX_MATCH_UDP_QUIC_DST_V4 \
    CTL_CODE(FILE_DEVICE_NETWORK, 28, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_RX_MATCH_PARAMS

#define IOCTL_GENERIC_RX_MATCH_UDP_QUIC_DST_V6 \
    CTL_CODE(FILE_DEVICE_NETWORK, 29, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_RX_MATCH_PARAMS

#define IOCTL_GENERIC_RX_MATCH_TCP_QUIC_SRC_V4 \
    CTL_CODE(FILE_DEVICE_NETWORK, 30, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_RX_MATCH_PARAMS

#define IOCTL_GENERIC_RX_MATCH_TCP_QUIC_SRC_V6 \
    CTL_CODE(FILE_DEVICE_NETWORK, 31, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_RX_MATCH_PARAMS

#define IOCTL_GENERIC_RX_MATCH_TCP_QUIC_DST_V4 \
    CTL_CODE(FILE_DEVICE_NETWORK, 32, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_RX_MATCH_PARAMS

#define IOCTL_GENERIC_RX_MATCH_TCP_QUIC_DST_V6 \
    CTL_CODE(FILE_DEVICE_NETWORK, 33, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_RX_MATCH_PARAMS

#define IOCTL_GENERIC_RX_MATCH_IP_PREFIX_V4 \
    CTL_CODE(FILE_DEVICE_NETWORK, 34, METHOD_BUFFERED, FILE_WRITE_DATA)
    // ADDRESS_FAMILY

#define IOCTL_GENERIC_RX_MATCH_IP_PREFIX_V6 \
    CTL_CODE(FILE_DEVICE_NETWORK, 35, METHOD_BUFFERED, FILE_WRITE_DATA)
    // ADDRESS_FAMILY

#define IOCTL_GENERIC_RX_MATCH_UDP_PORT_SET_V4 \
    CTL_CODE(FILE_DEVICE_NETWORK, 36, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_RX_MATCH_PARAMS

#define IOCTL_GENERIC_RX_MATCH_UDP_PORT_SET_V6 \
    CTL_CODE(FILE_DEVICE_NETWORK, 37, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_RX_MATCH_PARAMS

#define IOCTL_GENERIC_RX_MATCH_IPV4_UDP_PORT_SET \
    CTL_CODE(FILE_DEVICE_NETWORK, 38, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_RX_MATCH_PARAMS

#define IOCTL_GENERIC_RX_MATCH_IPV6_UDP_PORT_SET \
    CTL_CODE(FILE_DEVICE_NETWORK, 39, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_RX_MATCH_PARAMS

#define IOCTL_GENERIC_RX_MATCH_IPV4_TCP_PORT_SET \
    CTL_CODE(FILE_DEVICE_NETWORK, 40, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_RX_MATCH_PARAMS

#define IOCTL_GENERIC_RX_MATCH_IPV6_TCP_PORT_SET \
    CTL_CODE(FILE_DEVICE_NETWORK, 41, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_RX_MATCH_PARAMS

#define IOCTL_GENERIC_RX_MATCH_TCP_PORT_V4 \
    CTL_CODE(FILE_DEVICE_NETWORK, 42, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_RX_MATCH_PARAMS

#define IOCTL_GENERIC_RX_MATCH_TCP_PORT_V6 \
    CTL_CODE(FILE_DEVICE_NETWORK, 43, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_RX_MATCH_PARAMS

typedef struct {
    BOOLEAN Rx;
    BOOLEAN Tx;
} GENERIC_XSK_WAIT_PARAMS;

#define IOCTL_GENERIC_XSK_WAIT_RX \
    CTL_CODE(FILE_DEVICE_NETWORK, 44, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_XSK_WAIT_PARAMS

#define IOCTL_GENERIC_XSK_WAIT_TX \
    CTL_CODE(FILE_DEVICE_NETWORK, 45, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_XSK_WAIT_PARAMS

#define IOCTL_GENERIC_XSK_WAIT_RX_TX \
    CTL_CODE(FILE_DEVICE_NETWORK, 46, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_XSK_WAIT_PARAMS

#define IOCTL_GENERIC_XSK_WAIT_ASYNC_RX \
    CTL_CODE(FILE_DEVICE_NETWORK, 47, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_XSK_WAIT_PARAMS

#define IOCTL_GENERIC_XSK_WAIT_ASYNC_TX \
    CTL_CODE(FILE_DEVICE_NETWORK, 48, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_XSK_WAIT_PARAMS

#define IOCTL_GENERIC_XSK_WAIT_ASYNC_RX_TX \
    CTL_CODE(FILE_DEVICE_NETWORK, 49, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_XSK_WAIT_PARAMS

#define IOCTL_GENERIC_LWF_DELAY_DETACH_RX \
    CTL_CODE(FILE_DEVICE_NETWORK, 50, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_XSK_WAIT_PARAMS

#define IOCTL_GENERIC_LWF_DELAY_DETACH_TX \
    CTL_CODE(FILE_DEVICE_NETWORK, 51, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_XSK_WAIT_PARAMS

#define IOCTL_GENERIC_LWF_DELAY_DETACH_RX_TX \
    CTL_CODE(FILE_DEVICE_NETWORK, 52, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_XSK_WAIT_PARAMS

typedef struct {
    ADDRESS_FAMILY Af;
    BOOLEAN IsUdp;    
} GENERIC_RX_FRAGMENT_PARAMS;

#define IOCTL_GENERIC_RX_UDP_FRAGMENT_QUIC_LONG_HEADER_V4 \
    CTL_CODE(FILE_DEVICE_NETWORK, 53, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_RX_FRAGMENT_PARAMS

#define IOCTL_GENERIC_RX_UDP_FRAGMENT_QUIC_LONG_HEADER_V6 \
    CTL_CODE(FILE_DEVICE_NETWORK, 54, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_RX_FRAGMENT_PARAMS

#define IOCTL_GENERIC_RX_TCP_FRAGMENT_QUIC_LONG_HEADER_V4 \
    CTL_CODE(FILE_DEVICE_NETWORK, 55, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_RX_FRAGMENT_PARAMS

#define IOCTL_GENERIC_RX_TCP_FRAGMENT_QUIC_LONG_HEADER_V6 \
    CTL_CODE(FILE_DEVICE_NETWORK, 56, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_RX_FRAGMENT_PARAMS

#define IOCTL_GENERIC_RX_UDP_FRAGMENT_QUIC_SHORT_HEADER_V4 \
    CTL_CODE(FILE_DEVICE_NETWORK, 57, METHOD_BUFFERED, FILE_WRITE_DATA)
    // ADDRESS_FAMILY

#define IOCTL_GENERIC_RX_UDP_FRAGMENT_QUIC_SHORT_HEADER_V6 \
    CTL_CODE(FILE_DEVICE_NETWORK, 58, METHOD_BUFFERED, FILE_WRITE_DATA)
    // ADDRESS_FAMILY

#define IOCTL_GENERIC_RX_UDP_FRAGMENT_HEADER_DATA_V4 \
    CTL_CODE(FILE_DEVICE_NETWORK, 59, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_RX_FRAGMENT_PARAMS

#define IOCTL_GENERIC_RX_UDP_FRAGMENT_HEADER_DATA_V6 \
    CTL_CODE(FILE_DEVICE_NETWORK, 60, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_RX_FRAGMENT_PARAMS

#define IOCTL_GENERIC_RX_TCP_FRAGMENT_HEADER_DATA_V4 \
    CTL_CODE(FILE_DEVICE_NETWORK, 61, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_RX_FRAGMENT_PARAMS

#define IOCTL_GENERIC_RX_TCP_FRAGMENT_HEADER_DATA_V6 \
    CTL_CODE(FILE_DEVICE_NETWORK, 62, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_RX_FRAGMENT_PARAMS

#define IOCTL_GENERIC_RX_UDP_TOO_MANY_FRAGMENTS_V4 \
    CTL_CODE(FILE_DEVICE_NETWORK, 63, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_RX_FRAGMENT_PARAMS

#define IOCTL_GENERIC_RX_UDP_TOO_MANY_FRAGMENTS_V6 \
    CTL_CODE(FILE_DEVICE_NETWORK, 64, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_RX_FRAGMENT_PARAMS

#define IOCTL_GENERIC_RX_TCP_TOO_MANY_FRAGMENTS_V4 \
    CTL_CODE(FILE_DEVICE_NETWORK, 65, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_RX_FRAGMENT_PARAMS

#define IOCTL_GENERIC_RX_TCP_TOO_MANY_FRAGMENTS_V6 \
    CTL_CODE(FILE_DEVICE_NETWORK, 66, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_RX_FRAGMENT_PARAMS

typedef struct {
    ADDRESS_FAMILY Af;
    XDP_RULE_ACTION ProgramAction;
    BOOLEAN IsUdp;
    BOOLEAN IsTxInspect;    // = FALSE
    BOOLEAN IsLowResources; // = FALSE
} GENERIC_RX_PARAMS;

#define IOCTL_GENERIC_RX_UDP_HEADER_FRAGMENTS_V4 \
    CTL_CODE(FILE_DEVICE_NETWORK, 67, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_RX_PARAMS

#define IOCTL_GENERIC_RX_UDP_HEADER_FRAGMENTS_V6 \
    CTL_CODE(FILE_DEVICE_NETWORK, 68, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_RX_PARAMS

#define IOCTL_GENERIC_RX_TCP_HEADER_FRAGMENTS_V4 \
    CTL_CODE(FILE_DEVICE_NETWORK, 69, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_RX_PARAMS

#define IOCTL_GENERIC_RX_TCP_HEADER_FRAGMENTS_V6 \
    CTL_CODE(FILE_DEVICE_NETWORK, 70, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_RX_PARAMS

#define IOCTL_GENERIC_RX_L2_FWD \
    CTL_CODE(FILE_DEVICE_NETWORK, 71, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_RX_PARAMS

#define IOCTL_GENERIC_RX_L2_FWD_LOW_RESOURCES \
    CTL_CODE(FILE_DEVICE_NETWORK, 72, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_RX_PARAMS

#define IOCTL_GENERIC_RX_L2_FWD_TX_INSPECT \
    CTL_CODE(FILE_DEVICE_NETWORK, 73, METHOD_BUFFERED, FILE_WRITE_DATA)
    // GENERIC_RX_PARAMS

#define IOCTL_GENERIC_RX_FROM_TX_INSPECT_V4 \
    CTL_CODE(FILE_DEVICE_NETWORK, 74, METHOD_BUFFERED, FILE_WRITE_DATA)
    // ADDRESS_FAMILY

#define IOCTL_GENERIC_RX_FROM_TX_INSPECT_V6 \
    CTL_CODE(FILE_DEVICE_NETWORK, 75, METHOD_BUFFERED, FILE_WRITE_DATA)
    // ADDRESS_FAMILY

#define IOCTL_GENERIC_LOOPBACK_V4 \
    CTL_CODE(FILE_DEVICE_NETWORK, 76, METHOD_BUFFERED, FILE_WRITE_DATA)
    // ADDRESS_FAMILY

#define IOCTL_GENERIC_LOOPBACK_V6 \
    CTL_CODE(FILE_DEVICE_NETWORK, 77, METHOD_BUFFERED, FILE_WRITE_DATA)
    // ADDRESS_FAMILY

#define IOCTL_OFFLOAD_RSS_ERROR \
    CTL_CODE(FILE_DEVICE_NETWORK, 78, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_OFFLOAD_RSS_REFERENCE \
    CTL_CODE(FILE_DEVICE_NETWORK, 79, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_OFFLOAD_RSS_INTERFACE_RESTART \
    CTL_CODE(FILE_DEVICE_NETWORK, 80, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_OFFLOAD_RSS_UNCHANGED \
    CTL_CODE(FILE_DEVICE_NETWORK, 81, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_OFFLOAD_RSS_UPPER_SET \
    CTL_CODE(FILE_DEVICE_NETWORK, 82, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_OFFLOAD_RSS_SET \
    CTL_CODE(FILE_DEVICE_NETWORK, 83, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_OFFLOAD_RSS_CAPABILITIES \
    CTL_CODE(FILE_DEVICE_NETWORK, 84, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_OFFLOAD_RSS_RESET \
    CTL_CODE(FILE_DEVICE_NETWORK, 85, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_OFFLOAD_SET_HARDWARE_CAPABILITIES \
    CTL_CODE(FILE_DEVICE_NETWORK, 86, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_GENERIC_XSK_QUERY_AFFINITY \
    CTL_CODE(FILE_DEVICE_NETWORK, 87, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_OFFLOAD_QEO_CONNECTION \
    CTL_CODE(FILE_DEVICE_NETWORK, 88, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_OFFLOAD_QEO_REVERT_INTERFACE_REMOVAL \
    CTL_CODE(FILE_DEVICE_NETWORK, 89, METHOD_BUFFERED, FILE_WRITE_DATA)
    // REVERT_REASON

#define IOCTL_OFFLOAD_QEO_REVERT_HANDLE_CLOSURE \
    CTL_CODE(FILE_DEVICE_NETWORK, 90, METHOD_BUFFERED, FILE_WRITE_DATA)
    // REVERT_REASON

#define IOCTL_OFFLOAD_QEO_OID_FAILURE \
    CTL_CODE(FILE_DEVICE_NETWORK, 91, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_SECURITY_ADJUST_DEVICE_ACL \
    CTL_CODE(FILE_DEVICE_NETWORK, 92, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_GENERIC_RX_EBPF_ATTACH \
    CTL_CODE(FILE_DEVICE_NETWORK, 93, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_GENERIC_RX_EBPF_DROP \
    CTL_CODE(FILE_DEVICE_NETWORK, 94, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_GENERIC_RX_EBPF_PASS \
    CTL_CODE(FILE_DEVICE_NETWORK, 95, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_GENERIC_RX_EBPF_TX \
    CTL_CODE(FILE_DEVICE_NETWORK, 96, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_GENERIC_RX_EBPF_PAYLOAD \
    CTL_CODE(FILE_DEVICE_NETWORK, 97, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_PROG_TEST_RUN_RX_EBPF_PAYLOAD \
    CTL_CODE(FILE_DEVICE_NETWORK, 98, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_GENERIC_RX_EBPF_IF_INDEX \
    CTL_CODE(FILE_DEVICE_NETWORK, 99, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_GENERIC_RX_EBPF_FRAGMENTS \
    CTL_CODE(FILE_DEVICE_NETWORK, 100, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_GENERIC_RX_EBPF_UNLOAD \
    CTL_CODE(FILE_DEVICE_NETWORK, 101, METHOD_BUFFERED, FILE_WRITE_DATA)

#define MAX_IOCTL_FUNC_CODE 101

EXTERN_C_END
