# This template contains steps to build the XDP WPA plugin.

jobs:
- job: build_xdpetwplugin
  displayName: Any CPU
  pool:
    vmImage: windows-2022
  steps:
  - checkout: self

  - task: PowerShell@2
    displayName: Prepare Machine
    inputs:
      filePath: tools/prepare-machine.ps1
      arguments: -ForBuild -Verbose

  # Attempt to work around unreliable NuGet restore by refreshing the credential provider.
  - task: NuGetAuthenticate@1
    inputs:
      forceReinstallCredentialProvider: true

  - task: DotNetCoreCLI@2
    continueOnError: true
    inputs:
      projects: src\xdpetwplugin\xdpetwplugin.sln
      command: build
      arguments: "-c debug"

  - task: DotNetCoreCLI@2
    continueOnError: true
    inputs:
      projects: src\xdpetwplugin\xdpetwplugin.sln
      command: build
      arguments: "-c release"

  - task: CopyFiles@2
    displayName: Filter Artifacts
    inputs:
      sourceFolder: artifacts/bin
      contents: '**/!(*.ilk|*.exp|*.lastcodeanalysissucceeded)'
      targetFolder: $(Build.ArtifactStagingDirectory)/bin

  - task: PublishBuildArtifacts@1
    displayName: Upload Artifacts
    inputs:
      artifactName: artifacts
      pathToPublish: $(Build.ArtifactStagingDirectory)
      parallel: true
