# This template creates the release artifacts.

parameters:
  arch: 'x64'
  config: 'Debug'
  vmImage: 'windows-2022'

jobs:
- job: kits_${{ parameters.arch }}_${{ parameters.config }}
  displayName: kits
  pool:
    vmImage: ${{ parameters.vmImage }}
  variables:
  - name: runCodesignValidationInjection
    value: false
  steps:
  - checkout: self

  - task: DownloadBuildArtifacts@0
    displayName: Download Artifacts
    inputs:
      artifactName: artifacts
      itemPattern: artifacts/bin/${{ parameters.arch }}_${{ parameters.config }}/**
      downloadPath: $(Build.SourcesDirectory)

  - task: PowerShell@2
    displayName: Create Test Archive
    inputs:
      filePath: tools/create-test-archive.ps1
      arguments: -Config ${{ parameters.config }} -Platform ${{ parameters.arch }}

  - task: PublishBuildArtifacts@1
    displayName: Upload Kits
    inputs:
      artifactName: artifacts
      pathToPublish: artifacts/kit
      parallel: true

  - task: PublishBuildArtifacts@1
    displayName: Upload Test Archive
    inputs:
      artifactName: artifacts
      pathToPublish: artifacts/tests
      parallel: true
