# This template builds the dev kit.

parameters:
  arch: 'x64'
  config: 'Debug'

jobs:
- job: devkit_${{ parameters.arch }}_${{ parameters.config }}
  displayName: devkit
  pool:
    vmImage: windows-2019
  variables:
  - name: runCodesignValidationInjection
    value: false
  steps:
  - checkout: self

  - task: DownloadBuildArtifacts@0
    displayName: Download Artifacts
    inputs:
      artifactName: artifacts
      itemPattern: artifacts/bin/${{ parameters.arch }}_${{ parameters.config }}/**
      downloadPath: $(Build.SourcesDirectory)

  - task: PowerShell@2
    displayName: Create Dev Kit
    inputs:
      filePath: tools/create-devkit.ps1
      arguments: -Flavor ${{ parameters.config }} -Platform ${{ parameters.arch }}

  - task: PowerShell@2
    displayName: Create Runtime Kit
    inputs:
      filePath: tools/create-runtime-kit.ps1
      arguments: -Flavor ${{ parameters.config }} -Platform ${{ parameters.arch }}

  - task: PublishBuildArtifacts@1
    displayName: Upload Artifacts
    inputs:
      artifactName: artifacts
      pathToPublish: artifacts/kit
      parallel: true
