# This template runs spinxsk.exe for a single architecture.

parameters:
- name: pool
  default: ''
- name: image
  default: ''
- name: arch
  default: 'x64'
- name: config
  default: 'Debug'
- name: ignoreFailures
  type: boolean
  default: false
- name: runtimeMinutes
  type: number
  default: 10
- name: timeoutMinutes
  type: number
  default: 15
- name: jobTimeoutMinutes
  type: number
  default: 25
- name: successThresholdPercent
  type: number
  default: 1
- name: xdpmpPollProvider
  default: 'NDIS'
- name: osName

jobs:
- job: spinxsk__${{ parameters.arch }}_${{ parameters.config }}_${{ parameters.osName }}_${{ replace(parameters.pool, '-', '_') }}
  displayName: spinxsk-${{ parameters.osName }}-${{ parameters.arch }}_${{ parameters.config }} (${{ parameters.pool }})

  # Either run on our self-hosted 'pool' or an AZP managed 'image'.
  ${{ if ne(parameters.pool, '') }}:
    pool:
      name: ${{ parameters.pool }}
      ${{ if ne(parameters.image, '') }}:
        demands: ImageOverride -equals ${{ parameters.image }}
    workspace:
      clean: all
  ${{ if eq(parameters.pool, '') }}:
    pool:
      vmImage: ${{ parameters.image }}
  continueOnError: ${{ parameters.ignoreFailures }}
  variables:
    runCodesignValidationInjection: false
    logMode: 'File'
  timeoutInMinutes: ${{ parameters.jobTimeoutMinutes }}
  steps:
  - checkout: self

  - task: PowerShell@2
    displayName: Prepare Machine
    inputs:
      filePath: tools/prepare-machine.ps1
      arguments: -ForSpinxskTest -NoReboot -Verbose

  - task: PowerShell@2
    displayName: Check Drivers
    inputs:
      filePath: tools/check-drivers.ps1
      arguments: -Verbose -Config ${{ parameters.config }} -Arch ${{ parameters.arch }}

  - task: DownloadBuildArtifacts@0
    displayName: Download Artifacts
    inputs:
      artifactName: artifacts
      itemPattern: artifacts/bin/${{ parameters.arch }}_${{ parameters.config }}/**
      downloadPath: $(Build.SourcesDirectory)

  - task: PowerShell@2
    displayName: Run spinxsk
    timeoutInMinutes: ${{ parameters.timeoutMinutes }}
    continueOnError: ${{ parameters.ignoreFailures }}
    inputs:
      filePath: tools/spinxsk.ps1
      arguments: -Config ${{ parameters.config }} -Arch ${{ parameters.arch }} -QueueCount 2
        -Minutes ${{ parameters.runtimeMinutes }} -XdpmpPollProvider ${{ parameters.xdpmpPollProvider }}
        -Verbose -Stats -SuccessThresholdPercent ${{ parameters.successThresholdPercent }}
        -EnableEbpf

  - task: PowerShell@2
    displayName: Convert logs
    timeoutInMinutes: 5
    condition: always()
    inputs:
      filePath: tools/log.ps1
      arguments: -Convert -Name spinxsk -Verbose -Config ${{ parameters.config }} -Arch ${{ parameters.arch }}

  - task: CopyFiles@2
    displayName: Stage Logs
    condition: always()
    inputs:
      sourceFolder: artifacts/logs
      contents: '**/!(*.ilk|*.exp|*.lastcodeanalysissucceeded)'
      targetFolder: $(Build.ArtifactStagingDirectory)/logs/spinxsk_${{ parameters.arch }}_${{ parameters.config }}_${{ parameters.osName }}_${{ parameters.pool }}

  - task: PublishBuildArtifacts@1
    displayName: Upload Logs
    condition: always()
    inputs:
      artifactName: artifacts
      pathToPublish: $(Build.ArtifactStagingDirectory)
      parallel: true

  - task: PowerShell@2
    displayName: Cleanup Machine
    condition: always()
    inputs:
      filePath: tools/prepare-machine.ps1
      arguments: -Cleanup -ForTest -NoReboot

  - task: PowerShell@2
    displayName: Reboot (if necessary)
    condition: and(always(), eq(variables['NeedsReboot'],'true'))
    inputs:
      targetType: inline
      script: shutdown.exe /f /r /t 0 /c 'XDP Pipeline' /d u:4:5

  - task: PowerShell@2
    displayName: Check Drivers
    condition: always()
    inputs:
      filePath: tools/check-drivers.ps1
      arguments: -Verbose -Config ${{ parameters.config }} -Arch ${{ parameters.arch }}
