# This template runs xdpfunctionaltests.dll for a single architecture.

parameters:
  pool: ''
  image: ''
  arch: 'x64'
  config: 'Debug'
  ignoreFailures: false
  timeoutInMinutes: 10
  iterations: 1
  osName:

jobs:
- job: tests_${{ parameters.arch }}_${{ parameters.config }}_${{ parameters.osName }}_${{ replace(parameters.pool, '-', '_') }}
  displayName: functional-${{ parameters.osName }}-${{ parameters.arch }}_${{ parameters.config }} (${{ parameters.pool }})
  # Either run on our self-hosted 'pool' or an AZP managed 'image'.
  ${{ if ne(parameters.pool, '') }}:
    pool:
      name: ${{ parameters.pool }}
      ${{ if ne(parameters.image, '') }}:
        demands: ImageOverride -equals ${{ parameters.image }}
    workspace:
      clean: all
  ${{ if eq(parameters.pool, '') }}:
    pool:
      vmImage: ${{ parameters.image }}
  continueOnError: ${{ parameters.ignoreFailures }}
  variables:
  - name: runCodesignValidationInjection
    value: false
  steps:
  - checkout: self

  - task: PowerShell@2
    displayName: Prepare Machine
    inputs:
      filePath: tools/prepare-machine.ps1
      arguments: -ForFunctionalTest -NoReboot -Verbose

  - task: PowerShell@2
    displayName: Check Drivers
    inputs:
      filePath: tools/check-drivers.ps1
      arguments: -Verbose -Config ${{ parameters.config }} -Arch ${{ parameters.arch }}

  - task: DownloadBuildArtifacts@0
    displayName: Download Artifacts
    inputs:
      artifactName: artifacts
      itemPattern: artifacts/bin/${{ parameters.arch }}_${{ parameters.config }}/**
      downloadPath: $(Build.SourcesDirectory)

  - task: PowerShell@2
    displayName: Run Tests
    timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
    inputs:
      filePath: tools/functional.ps1
      arguments: -Verbose -Config ${{ parameters.config }} -Arch ${{ parameters.arch }} -Iterations ${{ parameters.iterations }} -Timeout ${{ parameters.timeoutInMinutes }}

  - task: PowerShell@2
    displayName: Convert Logs
    condition: always()
    timeoutInMinutes: 5
    inputs:
      filePath: tools/log.ps1
      arguments: -Convert -Name xdpfunc* -Verbose -Config ${{ parameters.config }} -Arch ${{ parameters.arch }}

  - task: CopyFiles@2
    displayName: Stage Logs
    condition: succeededOrFailed()
    inputs:
      sourceFolder: artifacts/logs
      contents: '**/!(*.ilk|*.exp|*.lastcodeanalysissucceeded)'
      targetFolder: $(Build.ArtifactStagingDirectory)/logs/${{ parameters.arch }}_${{ parameters.config }}_${{ parameters.osName }}_${{ parameters.pool }}

  - task: PublishBuildArtifacts@1
    displayName: Upload Logs
    condition: succeededOrFailed()
    inputs:
      artifactName: artifacts
      pathToPublish: $(Build.ArtifactStagingDirectory)
      parallel: true

  - task: PublishTestResults@2
    displayName: Publish Test Results
    condition: succeededOrFailed()
    inputs:
      testRunner: VSTest
      testResultsFiles: '*.trx'
      searchFolder: artifacts/logs
      failTaskOnFailedTests: true

  - task: PowerShell@2
    displayName: Cleanup Machine
    condition: always()
    inputs:
      filePath: tools/prepare-machine.ps1
      arguments: -Cleanup -ForTest -NoReboot

  - task: PowerShell@2
    displayName: Check Drivers
    condition: always()
    inputs:
      filePath: tools/check-drivers.ps1
      arguments: -Verbose -Config ${{ parameters.config }} -Arch ${{ parameters.arch }}
