//
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//

using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using Microsoft.Performance.SDK.Processing;

namespace XdpEtw
{
    /// <summary>
    /// This custom data source defines processes XDP ETW events.
    /// </summary>
    [ProcessingSource(
        "{e8e6cb29-9cf2-4b53-8b64-05e40b233149}",
        "XDP ETW Event",
        "ETW events generated by XDP")]
    [FileDataSource("etl", "Event Trace Log")]
    public class XdpEtwSource : ProcessingSource
    {
        private IApplicationEnvironment? applicationEnvironment;

        protected override ICustomDataProcessor CreateProcessorCore(
            IEnumerable<IDataSource> dataSources,
            IProcessorEnvironment processorEnvironment,
            ProcessorOptions options)
        {
            Debug.Assert(!(applicationEnvironment is null));

            return new XdpEventProcessor(
                new XdpEventParser(dataSources.Select(x => x.Uri.LocalPath).ToArray()),
                options,
                applicationEnvironment,
                processorEnvironment);
        }

        /// <summary>
        /// This method is called to perform additional checks on the data source, to confirm that the data is contains
        /// can be processed. This is helpful for common file extensions, such as ".xml" or ".log". This method could
        /// peek inside at the contents confirm whether it is associated with this custom data source.
        ///
        /// For this sample, we just assume that if the file name is a match, it is handled by this add-in.
        /// </summary>
        /// <param name="dataSource">Path to the source file</param>
        /// <returns>true when <param name="dataSource"> is handled by this add-in</param></returns>
        protected override bool IsDataSourceSupportedCore(IDataSource dataSource)
        {
            return true;
        }

        /// <summary>
        /// This method just saves the application environment so that it can be used later.
        /// </summary>
        /// <param name="applicationEnvironment">Contains information helpful to future processing</param>
        protected override void SetApplicationEnvironmentCore(IApplicationEnvironment applicationEnvironment)
        {
            this.applicationEnvironment = applicationEnvironment;
        }
    }
}
