// Copyright (C) Microsoft Corporation. All rights reserved.

//
// NOTE: This header is generated by stubwork.  Please make any 
//       modifications to the corresponding template files 
//       (.x or .y) and use stubwork to regenerate the header
//

#ifndef _NETREQUESTPREVIEW_2_0_H_
#define _NETREQUESTPREVIEW_2_0_H_

#ifndef WDF_EXTERN_C
  #ifdef __cplusplus
    #define WDF_EXTERN_C       extern "C"
    #define WDF_EXTERN_C_START extern "C" {
    #define WDF_EXTERN_C_END   }
  #else
    #define WDF_EXTERN_C
    #define WDF_EXTERN_C_START
    #define WDF_EXTERN_C_END
  #endif
#endif

WDF_EXTERN_C_START





DECLARE_HANDLE(NETREQUEST);


//
// NET Function: NetAdapterInitSetNetRequestAttributes
//
typedef
_IRQL_requires_max_(PASSIVE_LEVEL)
WDFAPI
void
(NTAPI *PFN_NETADAPTERINITSETNETREQUESTATTRIBUTES)(
    _In_
    PNET_DRIVER_GLOBALS DriverGlobals,
    _Inout_
    NETADAPTER_INIT* AdapterInit,
    _In_
    WDF_OBJECT_ATTRIBUTES* NetRequestAttributes
    );

_IRQL_requires_max_(PASSIVE_LEVEL)
FORCEINLINE
void
NetAdapterInitSetNetRequestAttributes(
    _Inout_
    NETADAPTER_INIT* AdapterInit,
    _In_
    WDF_OBJECT_ATTRIBUTES* NetRequestAttributes
    )
{
    ((PFN_NETADAPTERINITSETNETREQUESTATTRIBUTES) NetFunctions[NetAdapterInitSetNetRequestAttributesTableIndex])(NetDriverGlobals, AdapterInit, NetRequestAttributes);
}

//
// NET Function: NetRequestRetrieveInputOutputBuffer
//
typedef
_IRQL_requires_max_(DISPATCH_LEVEL)
WDFAPI
NTSTATUS
(NTAPI *PFN_NETREQUESTRETRIEVEINPUTOUTPUTBUFFER)(
    _In_
    PNET_DRIVER_GLOBALS DriverGlobals,
    _In_
    NETREQUEST Request,
    _In_
    UINT MininumInputLengthRequired,
    _In_
    UINT MininumOutputLengthRequired,
    _Outptr_result_bytebuffer_(max(*InputBufferLength,*OutputBufferLength))
    PVOID* InputOutputBuffer,
    _Out_opt_
    UINT* InputBufferLength,
    _Out_opt_
    UINT* OutputBufferLength
    );

_IRQL_requires_max_(DISPATCH_LEVEL)
FORCEINLINE
NTSTATUS
NetRequestRetrieveInputOutputBuffer(
    _In_
    NETREQUEST Request,
    _In_
    UINT MininumInputLengthRequired,
    _In_
    UINT MininumOutputLengthRequired,
    _Outptr_result_bytebuffer_(max(*InputBufferLength,*OutputBufferLength))
    PVOID* InputOutputBuffer,
    _Out_opt_
    UINT* InputBufferLength,
    _Out_opt_
    UINT* OutputBufferLength
    )
{
    return ((PFN_NETREQUESTRETRIEVEINPUTOUTPUTBUFFER) NetFunctions[NetRequestRetrieveInputOutputBufferTableIndex])(NetDriverGlobals, Request, MininumInputLengthRequired, MininumOutputLengthRequired, InputOutputBuffer, InputBufferLength, OutputBufferLength);
}

//
// NET Function: NetRequestWdmGetNdisOidRequest
//
typedef
_IRQL_requires_max_(DISPATCH_LEVEL)
WDFAPI
PNDIS_OID_REQUEST
(NTAPI *PFN_NETREQUESTWDMGETNDISOIDREQUEST)(
    _In_
    PNET_DRIVER_GLOBALS DriverGlobals,
    _In_
    NETREQUEST Request
    );

_IRQL_requires_max_(DISPATCH_LEVEL)
FORCEINLINE
PNDIS_OID_REQUEST
NetRequestWdmGetNdisOidRequest(
    _In_
    NETREQUEST Request
    )
{
    return ((PFN_NETREQUESTWDMGETNDISOIDREQUEST) NetFunctions[NetRequestWdmGetNdisOidRequestTableIndex])(NetDriverGlobals, Request);
}

//
// NET Function: NetRequestCompleteWithoutInformation
//
typedef
_IRQL_requires_max_(DISPATCH_LEVEL)
WDFAPI
void
(NTAPI *PFN_NETREQUESTCOMPLETEWITHOUTINFORMATION)(
    _In_
    PNET_DRIVER_GLOBALS DriverGlobals,
    _In_
    NETREQUEST Request,
    _In_
    NTSTATUS CompletionStatus
    );

_IRQL_requires_max_(DISPATCH_LEVEL)
FORCEINLINE
void
NetRequestCompleteWithoutInformation(
    _In_
    NETREQUEST Request,
    _In_
    NTSTATUS CompletionStatus
    )
{
    ((PFN_NETREQUESTCOMPLETEWITHOUTINFORMATION) NetFunctions[NetRequestCompleteWithoutInformationTableIndex])(NetDriverGlobals, Request, CompletionStatus);
}

//
// NET Function: NetRequestSetDataComplete
//
typedef
_IRQL_requires_max_(DISPATCH_LEVEL)
WDFAPI
void
(NTAPI *PFN_NETREQUESTSETDATACOMPLETE)(
    _In_
    PNET_DRIVER_GLOBALS DriverGlobals,
    _In_
    NETREQUEST Request,
    _In_
    NTSTATUS CompletionStatus,
    _In_
    UINT BytesRead
    );

_IRQL_requires_max_(DISPATCH_LEVEL)
FORCEINLINE
void
NetRequestSetDataComplete(
    _In_
    NETREQUEST Request,
    _In_
    NTSTATUS CompletionStatus,
    _In_
    UINT BytesRead
    )
{
    ((PFN_NETREQUESTSETDATACOMPLETE) NetFunctions[NetRequestSetDataCompleteTableIndex])(NetDriverGlobals, Request, CompletionStatus, BytesRead);
}

//
// NET Function: NetRequestQueryDataComplete
//
typedef
_IRQL_requires_max_(DISPATCH_LEVEL)
WDFAPI
void
(NTAPI *PFN_NETREQUESTQUERYDATACOMPLETE)(
    _In_
    PNET_DRIVER_GLOBALS DriverGlobals,
    _In_
    NETREQUEST Request,
    _In_
    NTSTATUS CompletionStatus,
    _In_
    UINT BytesWritten
    );

_IRQL_requires_max_(DISPATCH_LEVEL)
FORCEINLINE
void
NetRequestQueryDataComplete(
    _In_
    NETREQUEST Request,
    _In_
    NTSTATUS CompletionStatus,
    _In_
    UINT BytesWritten
    )
{
    ((PFN_NETREQUESTQUERYDATACOMPLETE) NetFunctions[NetRequestQueryDataCompleteTableIndex])(NetDriverGlobals, Request, CompletionStatus, BytesWritten);
}

//
// NET Function: NetRequestMethodComplete
//
typedef
_IRQL_requires_max_(DISPATCH_LEVEL)
WDFAPI
void
(NTAPI *PFN_NETREQUESTMETHODCOMPLETE)(
    _In_
    PNET_DRIVER_GLOBALS DriverGlobals,
    _In_
    NETREQUEST Request,
    _In_
    NTSTATUS CompletionStatus,
    _In_
    UINT BytesRead,
    _In_
    UINT BytesWritten
    );

_IRQL_requires_max_(DISPATCH_LEVEL)
FORCEINLINE
void
NetRequestMethodComplete(
    _In_
    NETREQUEST Request,
    _In_
    NTSTATUS CompletionStatus,
    _In_
    UINT BytesRead,
    _In_
    UINT BytesWritten
    )
{
    ((PFN_NETREQUESTMETHODCOMPLETE) NetFunctions[NetRequestMethodCompleteTableIndex])(NetDriverGlobals, Request, CompletionStatus, BytesRead, BytesWritten);
}

//
// NET Function: NetRequestSetBytesNeeded
//
typedef
_IRQL_requires_max_(DISPATCH_LEVEL)
WDFAPI
void
(NTAPI *PFN_NETREQUESTSETBYTESNEEDED)(
    _In_
    PNET_DRIVER_GLOBALS DriverGlobals,
    _In_
    NETREQUEST Request,
    _In_
    UINT BytesNeeded
    );

_IRQL_requires_max_(DISPATCH_LEVEL)
FORCEINLINE
void
NetRequestSetBytesNeeded(
    _In_
    NETREQUEST Request,
    _In_
    UINT BytesNeeded
    )
{
    ((PFN_NETREQUESTSETBYTESNEEDED) NetFunctions[NetRequestSetBytesNeededTableIndex])(NetDriverGlobals, Request, BytesNeeded);
}

//
// NET Function: NetRequestGetId
//
typedef
_IRQL_requires_max_(DISPATCH_LEVEL)
WDFAPI
NDIS_OID
(NTAPI *PFN_NETREQUESTGETID)(
    _In_
    PNET_DRIVER_GLOBALS DriverGlobals,
    _In_
    NETREQUEST Request
    );

_IRQL_requires_max_(DISPATCH_LEVEL)
FORCEINLINE
NDIS_OID
NetRequestGetId(
    _In_
    NETREQUEST Request
    )
{
    return ((PFN_NETREQUESTGETID) NetFunctions[NetRequestGetIdTableIndex])(NetDriverGlobals, Request);
}

//
// NET Function: NetRequestGetPortNumber
//
typedef
_IRQL_requires_max_(DISPATCH_LEVEL)
WDFAPI
NDIS_PORT_NUMBER
(NTAPI *PFN_NETREQUESTGETPORTNUMBER)(
    _In_
    PNET_DRIVER_GLOBALS DriverGlobals,
    _In_
    NETREQUEST Request
    );

_IRQL_requires_max_(DISPATCH_LEVEL)
FORCEINLINE
NDIS_PORT_NUMBER
NetRequestGetPortNumber(
    _In_
    NETREQUEST Request
    )
{
    return ((PFN_NETREQUESTGETPORTNUMBER) NetFunctions[NetRequestGetPortNumberTableIndex])(NetDriverGlobals, Request);
}

//
// NET Function: NetRequestGetSwitchId
//
typedef
_IRQL_requires_max_(DISPATCH_LEVEL)
WDFAPI
NDIS_NIC_SWITCH_ID
(NTAPI *PFN_NETREQUESTGETSWITCHID)(
    _In_
    PNET_DRIVER_GLOBALS DriverGlobals,
    _In_
    NETREQUEST Request
    );

_IRQL_requires_max_(DISPATCH_LEVEL)
FORCEINLINE
NDIS_NIC_SWITCH_ID
NetRequestGetSwitchId(
    _In_
    NETREQUEST Request
    )
{
    return ((PFN_NETREQUESTGETSWITCHID) NetFunctions[NetRequestGetSwitchIdTableIndex])(NetDriverGlobals, Request);
}

//
// NET Function: NetRequestGetVPortId
//
typedef
_IRQL_requires_max_(DISPATCH_LEVEL)
WDFAPI
NDIS_NIC_SWITCH_VPORT_ID
(NTAPI *PFN_NETREQUESTGETVPORTID)(
    _In_
    PNET_DRIVER_GLOBALS DriverGlobals,
    _In_
    NETREQUEST Request
    );

_IRQL_requires_max_(DISPATCH_LEVEL)
FORCEINLINE
NDIS_NIC_SWITCH_VPORT_ID
NetRequestGetVPortId(
    _In_
    NETREQUEST Request
    )
{
    return ((PFN_NETREQUESTGETVPORTID) NetFunctions[NetRequestGetVPortIdTableIndex])(NetDriverGlobals, Request);
}

//
// NET Function: NetRequestGetType
//
typedef
_IRQL_requires_max_(DISPATCH_LEVEL)
WDFAPI
NDIS_REQUEST_TYPE
(NTAPI *PFN_NETREQUESTGETTYPE)(
    _In_
    PNET_DRIVER_GLOBALS DriverGlobals,
    _In_
    NETREQUEST Request
    );

_IRQL_requires_max_(DISPATCH_LEVEL)
FORCEINLINE
NDIS_REQUEST_TYPE
NetRequestGetType(
    _In_
    NETREQUEST Request
    )
{
    return ((PFN_NETREQUESTGETTYPE) NetFunctions[NetRequestGetTypeTableIndex])(NetDriverGlobals, Request);
}

//
// NET Function: NetRequestGetAdapter
//
typedef
_IRQL_requires_max_(DISPATCH_LEVEL)
WDFAPI
NETADAPTER
(NTAPI *PFN_NETREQUESTGETADAPTER)(
    _In_
    PNET_DRIVER_GLOBALS DriverGlobals,
    _In_
    NETREQUEST Request
    );

_IRQL_requires_max_(DISPATCH_LEVEL)
FORCEINLINE
NETADAPTER
NetRequestGetAdapter(
    _In_
    NETREQUEST Request
    )
{
    return ((PFN_NETREQUESTGETADAPTER) NetFunctions[NetRequestGetAdapterTableIndex])(NetDriverGlobals, Request);
}




WDF_EXTERN_C_END

#endif // _NETREQUESTPREVIEW_2_0_H_

