# Continuous Integration (CI)

trigger:
  batch: true
  branches:
    include:
    - main
    - release/*
pr:
- main
- release/*

name: 0.$(Date:yyyy).$(Date:MM).$(DayOfMonth).$(Rev:rr).0

variables:
  ${{ if eq(variables['Build.Reason'], 'BatchedCI') }}:
    spinxskRuntime: 60
    spinxskTimeout: 65
    spinxskJobTimeout: 75
    functionalRuntime: 120
    functionalIterations: 10
  ${{ if ne(variables['Build.Reason'], 'BatchedCI') }}:
    spinxskRuntime: 10
    spinxskTimeout: 15
    spinxskJobTimeout: 25
    functionalRuntime: 15
    functionalIterations: 1

stages:

- stage: build_debug
  displayName: Build (Debug)
  dependsOn: []
  jobs:
  - template: ./templates/build.yml
    parameters:
      arch: x64
      config: Debug

- stage: build_release
  displayName: Build (Release)
  dependsOn: []
  jobs:
  - template: ./templates/build.yml
    parameters:
      arch: x64
      config: Release

# Some driver developers are building for WS2022 LTSC targets using VS2019 +
# the Windows Server 2022 WDK, so validate our project still builds in that
# environment.
- stage: build_ltsc_debug
  displayName: Build (VS2019 Debug)
  dependsOn: []
  jobs:
  - template: ./templates/build.yml
    parameters:
      arch: x64
      config: Debug
      vmImage: windows-2019
      publish: false

- stage: build_ltsc_release
  displayName: Build (VS2019 Release)
  dependsOn: []
  jobs:
  - template: ./templates/build.yml
    parameters:
      arch: x64
      config: Release
      vmImage: windows-2019
      publish: false

- stage: test_debug
  displayName: Functional Tests (Debug)
  dependsOn:
  - build_debug
  jobs:
  - template: ./templates/tests.yml
    parameters:
      pool: XDP-CI-1ES-Functional-2
      image: WS2019-Functional
      arch: x64
      config: Debug
      osName: 2019
      timeoutInMinutes: ${{ variables.functionalRuntime }}
      iterations: ${{ variables.functionalIterations }}
  - template: ./templates/tests.yml
    parameters:
      pool: XDP-CI-1ES-Functional-2
      image: WS2022-Functional
      arch: x64
      config: Debug
      osName: 2022
      timeoutInMinutes: ${{ variables.functionalRuntime }}
      iterations: ${{ variables.functionalIterations }}
  - template: ./templates/tests.yml
    parameters:
      pool: XDP-CI-1ES-Functional-2
      image: WSPrerelease-Functional
      arch: x64
      config: Debug
      osName: Prerelease
      timeoutInMinutes: ${{ variables.functionalRuntime }}
      iterations: ${{ variables.functionalIterations }}

- stage: test_release
  displayName: Functional Tests (Release)
  dependsOn:
  - build_release
  jobs:
  - template: ./templates/tests.yml
    parameters:
      pool: XDP-CI-1ES-Functional-2
      image: WS2019-Functional
      arch: x64
      config: Release
      osName: 2019
      timeoutInMinutes: ${{ variables.functionalRuntime }}
      iterations: ${{ variables.functionalIterations }}
  - template: ./templates/tests.yml
    parameters:
      pool: XDP-CI-1ES-Functional-2
      image: WS2022-Functional
      arch: x64
      config: Release
      osName: 2022
      timeoutInMinutes: ${{ variables.functionalRuntime }}
      iterations: ${{ variables.functionalIterations }}
  - template: ./templates/tests.yml
    parameters:
      pool: XDP-CI-1ES-Functional-2
      image: WSPrerelease-Functional
      arch: x64
      config: Release
      osName: Prerelease
      timeoutInMinutes: ${{ variables.functionalRuntime }}
      iterations: ${{ variables.functionalIterations }}

- stage: stress_debug
  displayName: Stress (Debug)
  dependsOn:
  - build_debug
  jobs:
  - template: ./templates/spinxsk.yml
    parameters:
      pool: XDP-CI-1ES-Spinxsk-2
      image: WS2019-Spinxsk
      arch: x64
      config: Debug
      osName: 2019
      xdpmpPollProvider: FNDIS
      runtimeMinutes: ${{ variables.spinxskRuntime }}
      timeoutMinutes: ${{ variables.spinxskTimeout }}
      jobTimeoutMinutes: ${{ variables.spinxskJobTimeout }}
  - template: ./templates/spinxsk.yml
    parameters:
      pool: XDP-CI-1ES-Spinxsk-2
      image: WS2022-Spinxsk
      arch: x64
      config: Debug
      osName: 2022
      xdpmpPollProvider: FNDIS
      runtimeMinutes: ${{ variables.spinxskRuntime }}
      timeoutMinutes: ${{ variables.spinxskTimeout }}
      jobTimeoutMinutes: ${{ variables.spinxskJobTimeout }}
  # Prerelease stress is disabled due to a Windows bug
  # - template: ./templates/spinxsk.yml
  #   parameters:
  #     pool: XDP-CI-1ES-Spinxsk-2
  #     image: WSPrerelease-Spinxsk
  #     arch: x64
  #     config: Debug
  #     osName: Prerelease
  #     runtimeMinutes: ${{ variables.spinxskRuntime }}
  #     timeoutMinutes: ${{ variables.spinxskTimeout }}
  #     jobTimeoutMinutes: ${{ variables.spinxskJobTimeout }}

- stage: stress_release
  displayName: Stress (Release)
  dependsOn:
  - build_release
  jobs:
  - template: ./templates/spinxsk.yml
    parameters:
      pool: XDP-CI-1ES-Spinxsk-2
      image: WS2019-Spinxsk
      arch: x64
      config: Release
      osName: 2019
      xdpmpPollProvider: FNDIS
      runtimeMinutes: ${{ variables.spinxskRuntime }}
      timeoutMinutes: ${{ variables.spinxskTimeout }}
      jobTimeoutMinutes: ${{ variables.spinxskJobTimeout }}
  - template: ./templates/spinxsk.yml
    parameters:
      pool: XDP-CI-1ES-Spinxsk-2
      image: WS2022-Spinxsk
      arch: x64
      config: Release
      osName: 2022
      xdpmpPollProvider: FNDIS
      runtimeMinutes: ${{ variables.spinxskRuntime }}
      timeoutMinutes: ${{ variables.spinxskTimeout }}
      jobTimeoutMinutes: ${{ variables.spinxskJobTimeout }}
  # Prerelease stress is disabled due to a Windows bug
  # - template: ./templates/spinxsk.yml
  #   parameters:
  #     pool: XDP-CI-1ES-Spinxsk-2
  #     image: WSPrerelease-Spinxsk
  #     arch: x64
  #     config: Release
  #     osName: Prerelease
  #     runtimeMinutes: ${{ variables.spinxskRuntime }}
  #     timeoutMinutes: ${{ variables.spinxskTimeout }}
  #     jobTimeoutMinutes: ${{ variables.spinxskJobTimeout }}

- stage: create_artifacts
  displayName: Create Artifacts
  dependsOn: build_release
  jobs:
  - template: ./templates/create-release-artifacts.yml
    parameters:
      arch: x64
      config: Release

- stage: etwplugin
  displayName: ETW Plugin
  dependsOn: []
  jobs:
  - template: ./templates/build-xdpetwplugin.yml
