#
# Copy release artifacts from the CI pipeline to a GitHub release.
#

name: 0.$(Date:yyyy).$(Date:MM).$(DayOfMonth).$(Rev:rr).0

trigger: none

resources:
  pipelines:
  - pipeline: ci_pipeline
    source: "CI"

steps:
  - download: ci_pipeline
    artifact: artifacts
    patterns: artifacts/xdp-@(devkit|runtime)-x64/xdp-@(devkit|runtime)-x64*.zip
  
  - task: GitHubRelease@1
    inputs:
      gitHubConnection: "GitHub - nibanks"
      repositoryName: "microsoft/xdp-for-windows"
      action: create
      target: $(resources.pipeline.ci_pipeline.sourceCommit)
      isPreRelease: true
      title: "main (prerelease)"
      tagSource: userSpecifiedTag
      tag: main-prerelease-$(resources.pipeline.ci_pipeline.sourceCommit)
      addChangeLog: false
      releaseNotesSource: inline
      releaseNotesInline: "Latest `main` build"
      assets: $(Pipeline.Workspace)/ci_pipeline/artifacts/**
