# Continuous Integration (CI)

trigger:
  batch: true
  branches:
    include:
    - main
    - release/*
pr:
- main
- release/*

name: 0.$(Date:yyyy).$(Date:MM).$(DayOfMonth).$(Rev:rr).0

variables:
  ${{ if eq(variables['Build.Reason'], 'BatchedCI') }}:
    spinxskRuntime: 60
    spinxskTimeout: 65
    spinxskJobTimeout: 75
    functionalRuntime: 60
    functionalIterations: 10
  ${{ if ne(variables['Build.Reason'], 'BatchedCI') }}:
    spinxskRuntime: 10
    spinxskTimeout: 15
    spinxskJobTimeout: 25
    functionalRuntime: 5
    functionalIterations: 1

stages:

- stage: build_debug
  displayName: Build (Debug)
  dependsOn: []
  jobs:
  - template: ./templates/build.yml
    parameters:
      arch: x64
      config: Debug

- stage: build_release
  displayName: Build (Release)
  dependsOn: []
  jobs:
  - template: ./templates/build.yml
    parameters:
      arch: x64
      config: Release

- stage: test_debug
  displayName: Functional Tests (Debug)
  dependsOn:
  - build_debug
  jobs:
  - template: ./templates/tests.yml
    parameters:
      pool: MsQuic
      arch: x64
      config: Debug
      osName: latest
      timeoutInMinutes: 10
      iterations: 1
  - template: ./templates/tests.yml
    parameters:
      pool: XDP-CI-1ES-Functional-2
      image: WS2019-Functional
      arch: x64
      config: Debug
      osName: 2019
      timeoutInMinutes: ${{ variables.functionalRuntime }}
      iterations: ${{ variables.functionalIterations }}
  - template: ./templates/tests.yml
    parameters:
      pool: XDP-CI-1ES-Functional-2
      image: WS2022-Functional
      arch: x64
      config: Debug
      osName: 2022
      timeoutInMinutes: ${{ variables.functionalRuntime }}
      iterations: ${{ variables.functionalIterations }}

- stage: test_release
  displayName: Functional Tests (Release)
  dependsOn:
  - build_release
  jobs:
  - template: ./templates/tests.yml
    parameters:
      pool: MsQuic
      arch: x64
      config: Release
      osName: latest
      timeoutInMinutes: 10
      iterations: 1
  - template: ./templates/tests.yml
    parameters:
      pool: XDP-CI-1ES-Functional-2
      image: WS2019-Functional
      arch: x64
      config: Release
      osName: 2019
      timeoutInMinutes: ${{ variables.functionalRuntime }}
      iterations: ${{ variables.functionalIterations }}
  - template: ./templates/tests.yml
    parameters:
      pool: XDP-CI-1ES-Functional-2
      image: WS2022-Functional
      arch: x64
      config: Release
      osName: 2022
      timeoutInMinutes: ${{ variables.functionalRuntime }}
      iterations: ${{ variables.functionalIterations }}

- stage: stress_debug
  displayName: Stress (Debug)
  dependsOn:
  - build_debug
  jobs:
  - template: ./templates/spinxsk.yml
    parameters:
      pool: MsQuic
      arch: x64
      config: Debug
      osName: latest
      runtimeMinutes: 2
      timeoutMinutes: 7
      jobTimeoutMinutes: 17
      successThresholdPercent: 50
  - template: ./templates/spinxsk.yml
    parameters:
      pool: XDP-CI-1ES-Spinxsk-2
      image: WS2019-Spinxsk
      arch: x64
      config: Debug
      osName: 2019
      xdpmpPollProvider: FNDIS
      runtimeMinutes: ${{ variables.spinxskRuntime }}
      timeoutMinutes: ${{ variables.spinxskTimeout }}
      jobTimeoutMinutes: ${{ variables.spinxskJobTimeout }}
  - template: ./templates/spinxsk.yml
    parameters:
      pool: XDP-CI-1ES-Spinxsk-2
      image: WS2022-Spinxsk
      arch: x64
      config: Debug
      osName: 2022
      xdpmpPollProvider: FNDIS
      runtimeMinutes: ${{ variables.spinxskRuntime }}
      timeoutMinutes: ${{ variables.spinxskTimeout }}
      jobTimeoutMinutes: ${{ variables.spinxskJobTimeout }}

- stage: stress_release
  displayName: Stress (Release)
  dependsOn:
  - build_release
  jobs:
  - template: ./templates/spinxsk.yml
    parameters:
      pool: MsQuic
      arch: x64
      config: Release
      osName: latest
      runtimeMinutes: 2
      timeoutMinutes: 7
      jobTimeoutMinutes: 17
      successThresholdPercent: 50
  - template: ./templates/spinxsk.yml
    parameters:
      pool: XDP-CI-1ES-Spinxsk-2
      image: WS2019-Spinxsk
      arch: x64
      config: Release
      osName: 2019
      xdpmpPollProvider: FNDIS
      runtimeMinutes: ${{ variables.spinxskRuntime }}
      timeoutMinutes: ${{ variables.spinxskTimeout }}
      jobTimeoutMinutes: ${{ variables.spinxskJobTimeout }}
  - template: ./templates/spinxsk.yml
    parameters:
      pool: XDP-CI-1ES-Spinxsk-2
      image: WS2022-Spinxsk
      arch: x64
      config: Release
      osName: 2022
      xdpmpPollProvider: FNDIS
      runtimeMinutes: ${{ variables.spinxskRuntime }}
      timeoutMinutes: ${{ variables.spinxskTimeout }}
      jobTimeoutMinutes: ${{ variables.spinxskJobTimeout }}

- stage: devkit
  displayName: Dev Kit
  dependsOn: build_release
  jobs:
  - template: ./templates/devkit.yml
    parameters:
      pool: MsQuic
      arch: x64
      config: Release

- stage: etwplugin
  displayName: ETW Plugin
  dependsOn: []
  jobs:
  - template: ./templates/build-xdpetwplugin.yml
