trigger: none # https://aka.ms/obpipelines/triggers

resources:
  pipelines:
  - pipeline: onebranch   # Name of the pipeline resource (?)
    source: Official.xdp-for-windows # Name of the pipeline referenced by the pipeline resource
    trigger: true

name: 0.$(Date:yyyy).$(Date:MM).$(DayOfMonth).$(Rev:rr).0

variables:
    spinxskRuntime: 60
    spinxskTimeout: 65
    spinxskJobTimeout: 75
    functionalRuntime: 180
    functionalIterations: 10

stages:
- stage: build
  displayName: Build
  jobs:
    strategy:
      matrix:
        x64_Debug:
          arch: x64
          config: Debug
        x64_Release:
          arch: x64
          config: Release
  steps:
    - template: ./templates/build.yml
      parameters:
        arch: $(arch)
        config: $(config)

- stage: test_debug
  displayName: Functional Tests (Debug)
  dependsOn:
  - build_debug
  jobs:
  - template: ./templates/tests.yml
    parameters:
      pool: XDP-CI-1ES-Functional-2
      image: WS2019-Functional
      arch: x64
      config: Debug
      osName: 2019
      timeoutInMinutes: ${{ variables.functionalRuntime }}
      iterations: ${{ variables.functionalIterations }}
  - template: ./templates/tests.yml
    parameters:
      pool: XDP-CI-1ES-Functional-2
      image: WS2022-Functional
      arch: x64
      config: Debug
      osName: 2022
      timeoutInMinutes: ${{ variables.functionalRuntime }}
      iterations: ${{ variables.functionalIterations }}
  - template: ./templates/tests.yml
    parameters:
      pool: XDP-CI-1ES-Functional-2
      image: WSPrerelease-Functional
      arch: x64
      config: Debug
      osName: Prerelease
      timeoutInMinutes: ${{ variables.functionalRuntime }}
      iterations: ${{ variables.functionalIterations }}

- stage: test_release
  displayName: Functional Tests (Release)
  dependsOn:
  - build_release
  jobs:
  - template: ./templates/tests.yml
    parameters:
      pool: XDP-CI-1ES-Functional-2
      image: WS2019-Functional
      arch: x64
      config: Release
      osName: 2019
      timeoutInMinutes: ${{ variables.functionalRuntime }}
      iterations: ${{ variables.functionalIterations }}
  - template: ./templates/tests.yml
    parameters:
      pool: XDP-CI-1ES-Functional-2
      image: WS2022-Functional
      arch: x64
      config: Release
      osName: 2022
      timeoutInMinutes: ${{ variables.functionalRuntime }}
      iterations: ${{ variables.functionalIterations }}
  - template: ./templates/tests.yml
    parameters:
      pool: XDP-CI-1ES-Functional-2
      image: WSPrerelease-Functional
      arch: x64
      config: Release
      osName: Prerelease
      timeoutInMinutes: ${{ variables.functionalRuntime }}
      iterations: ${{ variables.functionalIterations }}

- stage: stress_debug
  displayName: Stress (Debug)
  dependsOn:
  - build_debug
  jobs:
  - template: ./templates/spinxsk.yml
    parameters:
      pool: XDP-CI-1ES-Spinxsk-2
      image: WS2019-Spinxsk
      arch: x64
      config: Debug
      osName: 2019
      xdpmpPollProvider: FNDIS
      runtimeMinutes: ${{ variables.spinxskRuntime }}
      timeoutMinutes: ${{ variables.spinxskTimeout }}
      jobTimeoutMinutes: ${{ variables.spinxskJobTimeout }}
  - template: ./templates/spinxsk.yml
    parameters:
      pool: XDP-CI-1ES-Spinxsk-2
      image: WS2022-Spinxsk
      arch: x64
      config: Debug
      osName: 2022
      xdpmpPollProvider: FNDIS
      runtimeMinutes: ${{ variables.spinxskRuntime }}
      timeoutMinutes: ${{ variables.spinxskTimeout }}
      jobTimeoutMinutes: ${{ variables.spinxskJobTimeout }}
  - template: ./templates/spinxsk.yml
    parameters:
      pool: XDP-CI-1ES-Spinxsk-2
      image: WSPrerelease-Spinxsk
      arch: x64
      config: Debug
      osName: Prerelease
      runtimeMinutes: ${{ variables.spinxskRuntime }}
      timeoutMinutes: ${{ variables.spinxskTimeout }}
      jobTimeoutMinutes: ${{ variables.spinxskJobTimeout }}

- stage: stress_release
  displayName: Stress (Release)
  dependsOn:
  - build_release
  jobs:
  - template: ./templates/spinxsk.yml
    parameters:
      pool: XDP-CI-1ES-Spinxsk-2
      image: WS2019-Spinxsk
      arch: x64
      config: Release
      osName: 2019
      xdpmpPollProvider: FNDIS
      runtimeMinutes: ${{ variables.spinxskRuntime }}
      timeoutMinutes: ${{ variables.spinxskTimeout }}
      jobTimeoutMinutes: ${{ variables.spinxskJobTimeout }}
  - template: ./templates/spinxsk.yml
    parameters:
      pool: XDP-CI-1ES-Spinxsk-2
      image: WS2022-Spinxsk
      arch: x64
      config: Release
      osName: 2022
      xdpmpPollProvider: FNDIS
      runtimeMinutes: ${{ variables.spinxskRuntime }}
      timeoutMinutes: ${{ variables.spinxskTimeout }}
      jobTimeoutMinutes: ${{ variables.spinxskJobTimeout }}
  - template: ./templates/spinxsk.yml
    parameters:
      pool: XDP-CI-1ES-Spinxsk-2
      image: WSPrerelease-Spinxsk
      arch: x64
      config: Release
      osName: Prerelease
      runtimeMinutes: ${{ variables.spinxskRuntime }}
      timeoutMinutes: ${{ variables.spinxskTimeout }}
      jobTimeoutMinutes: ${{ variables.spinxskJobTimeout }}
