trigger: none # https://aka.ms/obpipelines/triggers

resources:
  pipelines:
  - pipeline: onebranch   # Name of the pipeline resource (?)
    source: Official.xdp-for-windows # Name of the pipeline referenced by the pipeline resource
    trigger: true

name: 0.$(Date:yyyy).$(Date:MM).$(DayOfMonth).$(Rev:rr).0

parameters:
- name: platforms
  type: object
  default:
  - x64

- name: configurations
  type: object
  default:
  - Debug
  - Release

- name: oses
  type: object
  default:
  - 2019
  - 2022
  - Prerelease

variables:
  spinxskRuntime: 60
  spinxskTimeout: 65
  spinxskJobTimeout: 75
  functionalRuntime: 180
  functionalIterations: 10

stages:
  - ${{ each platform in parameters.platforms }}:
    - ${{ each config in parameters.configurations }}:
      - stage: build_${{platform}}_${{config}}
        displayName: Build (${{platform}}_${{config}})
        dependsOn: []
        jobs:
        - template: ./templates/build.yml
          parameters:
            platform: ${{platform}}
            config: ${{config}}

      - ${{ each os in parameters.oses }}:
        - stage: functional_${{os}}_${{platform}}_${{config}}
          displayName: Functional ${{os}} (${{platform}}_${{config}})
          dependsOn:
          - build_${{platform}}_${{config}}
          jobs:
          - template: ./templates/tests.yml
            parameters:
              pool: XDP-CI-1ES-Functional-2
              image: WS${{os}}-Functional
              platform: ${{platform}}
              config: ${{config}}
              osName: ${{os}}
              timeoutInMinutes: ${{ variables.functionalRuntime }}
              iterations: ${{ variables.functionalIterations }}

        - stage: stress_${{os}}_${{platform}}_${{config}}
          displayName: Stress ${{os}} (${{platform}}_${{config}})
          dependsOn:
          - build_${{platform}}_${{config}}
          jobs:
          - template: ./templates/spinxsk.yml
            parameters:
              pool: XDP-CI-1ES-Spinxsk-2
              image: WS${{os}}-Spinxsk
              platform: ${{platform}}
              config: ${{config}}
              osName: ${{os}}
              runtimeMinutes: ${{ variables.spinxskRuntime }}
              timeoutMinutes: ${{ variables.spinxskTimeout }}
              jobTimeoutMinutes: ${{ variables.spinxskJobTimeout }}
              ${{ if eq(os, 'Prerelease') }}:
                xdpmpPollProvider: NDIS
              ${{ if ne(os, 'Prerelease') }}:
                xdpmpPollProvider: FNDIS
